FROM giovtorres/slurm-docker-cluster:latest

USER root

RUN yum clean all && \
    yum install -y epel-release && \
    yum install -y xterm which whiptail python3 python3-devel php-cli unzip curl python3-lib2to3 python3-toolz php-mbstring git && \
    yum clean all
