#!/usr/bin/env bash

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"
cd ..

DO=0

for acq_class in $(cat .omniopt.py | grep "VALID_ACQUISITION_CLASSES: list" | sed -e 's#.*=\s*##' | tr -d '[]" ' | tr ',' '\n'); do
	if [[ $DO -eq 1 ]]; then
		.tests/start_simple_optimization_run --num_parallel_jobs=1 --gpus=0 --num_random_steps=1 --max_eval=2 --mem_gb=4 --nr_results=1 --testname="test_acquisition_function_$acq_class" --additional_parameter="--acquisition_class $acq_class"
		exit_code=$?

		if [[ $exit_code != 0 ]]; then
			red_text "Acquisition class '$acq_class' failed. See stdout for more details."
			exit 1
		fi
	else
		if [[ $acq_class == "qLogNoisyExpectedImprovement" ]]; then
			DO=1
		else
			yellow_text "Skipping $acq_class"
		fi
	fi
done

green_text "All acquisition_classes worked"
exit 0
