#!/bin/bash

function echoerr() {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

function green_text {
	echoerr -e "\e\033[0;32m$1\e[0m"
}

if command -v php 2>/dev/null >/dev/null; then
	SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

	cd "$SCRIPT_DIR"

	cd ..

	gui_options="$(cat .gui/gui_data.js | grep "id:" | sed -e 's#.*:##' -e 's#",##' -e 's#"##' -e 's#^\s*##')"

	cd .gui
	help_options="$(php _tutorials/help.php | grep '<pre>--' | sed -e 's#.*<pre>--##' -e 's#</pre>.*##')"
	cd ..

	errors=0

	declare -a gui_exceptions=(
		constraints
		installation_method
	)

	declare -a help_exceptions=(
		raise_in_eval
		run_tests_that_fail_on_taurus
		tests
		parameter
		continue_previous_job
		orchestrator_file
		ui_url
		run_dir
		maximize
		signed_weighted_euclidean_weights
		experiment_constraints
		minkowski_p
		max_parallelism
		show_ram_every_n_seconds
	)

	for gui_option in $gui_options; do
		if printf '%s\n' "${help_options[@]}" | grep -qx "$gui_option" || printf '%s\n' "${gui_exceptions[@]}" | grep -qx "$gui_option"; then
			true
		else
			red_text "GUI option $gui_option is not in the --help"
			errors=$((errors+1))
		fi
	done

	for help_option in $help_options; do
		if printf '%s\n' "${gui_options[@]}" | grep -qx "$help_option" || printf '%s\n' "${help_exceptions[@]}" | grep -qx "$help_option"; then
			true
		else
			red_text "--help option $help_option is not in the GUI"
			errors=$((errors+1))
		fi
	done

	if [[ $errors -eq 0 ]]; then
		green_text "No errors"
		exit 0
	fi

	red_text "$errors errors"
	exit $errors
else
	green_text "PHP not installed. Will skip all_oo_options_are_in_gui_and_vice_versa."
	exit 0
fi
