#!/bin/bash

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

missing=0

for from_code in $(cat .omniopt.py | grep "^\s*write_state_file" | sed -e 's#,.*##' -e 's#^\s*write_state_file..##' -e 's#"##'); do
	md_file=".gui/_tutorials/folder_structure.md"
	if [[ $(cat $md_file | grep -- "^\s*-\s\`$from_code\`" | wc -l) -ne 1 ]]; then
		red_text "'$from_code' missing in $md_file"
		missing=$((missing+1))
	fi
done

exit $missing
