#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

source ../.colorfunctions.sh

export NO_WHIPTAIL=1
export NO_RUNTIME=1

if [[ ! -d "runs/" ]]; then
	red_text "runs is not a directory. Cannot continue"
	exit 1
fi

for plot_type in $(ls .omniopt_plot_*.py | grep -v 3d | sed -e 's#\.omniopt_plot_##' | sed -e 's#\.py##'); do
	for project in runs/*; do
		for project_nr in runs/$project/*; do
			yellow_text "./omniopt_plot --run_dir runs/$project/$project_nr --plot_type=$plot_type --no_plt_show"
			./omniopt_plot --run_dir runs/$project/$project_nr --plot_type=$plot_type --no_plt_show
		done
	done
done
