live_share = true
partition = "alpha"
experiment_name = "__main__tests__"
mem_gb = 4
time = 60
worker_timeout = 5
max_eval = 2
num_parallel_jobs = 20
gpus = 
run_program =


"./tests/optimization_example --int_param='%int_param' --float_param='%float_param' --choice_param='%choice_param' --int_param_two='%int_param_two'"

[parameter]]
name = "int_param"
type = "range"
min = -100
max = 10
data_type = "int"

[[parameter]]
name = "float_param"
type = "range"
min = -100
max = 10
data_type = "float"

[[parameter]]
name = "choice_param"
type = "choice"
choices = ["1", "2", "4", "8", 16", "hallo"]

[[parameter]]
name = "int_param_two"
type = "range"
min = -100
max = 10
data_type = "int"

num_random_steps = 1
model = ["BOTORCH_MODULAR"
auto_exclude_defective_hosts = true
