live_share: true
partition: alpha
experiment_name: __main__tests__
mem_gb: 4
time: 60
worker_timeout: 5
max_eval: 2
num_parallel_jobs: 20
gpus: 1
generate_all_jobs_at_once: true
run_program: >-
  ./.tests/optimization_example --int_param='%(int_param)'
  --float_param='%(float_param)' --choice_param='%(choice_param)'
  --int_param_two='%(int_param_two)'
parameter:
  - param:
      - int_param
      - range
      - '-100'
      - '10'
      - int
  - param:
      - float_param
      - range
      - '-100'
      - '10'
      - float
  - param:
      - choice_param
      - choice
      - '1,2,4,8,16,hallo'
  - param:
      - int_param_two
      - range
      - '-100'
      - '10'
      - int
    num_random_steps: 1
    model: BOTORCH_MODULAR
    auto_exclude_defective_hosts: true
