#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"

cd ..

./omniopt --partition=alpha --experiment_name=small_test_experiment --mem_gb=1 --time=60 --worker_timeout=60 --max_eval=2 --num_parallel_jobs=5 --gpus=1 --num_random_steps=1 --follow --live_share --send_anonymized_usage_stats --result_names RESULT=max --run_program=ZWNobyAiUkVTVUxUOiAlKHgpJSh5KSIgJiYgZWNobyAiUkVTVUxUMjogJXoi --cpus_per_task=1 --nodes_per_job=1 --generate_all_jobs_at_once --revert_to_random_when_seemingly_exhausted --model=EXTERNAL_GENERATOR --run_mode=local --decimalrounding=4 --occ_type=euclid --main_process_gb=8 --max_nr_of_zero_results=1 --pareto_front_confidence=1 --slurm_signal_delay_s=0 --n_estimators_randomforest=100 --parameter x range 123 100000000 int false --parameter y choice 5431,1234 --parameter z fixed 111 --external_generator $(echo "python3 $(pwd)/.tools/example_external.py" | base64 -w0)
