#!/usr/bin/env bash

# HELPPAGE: Test external generator.

MEM_GB=1
TIME=60
WORKER_TIMEOUT=60
MAX_EVAL=2
NUM_PARALLEL_JOBS=1
NUM_GPUS=1
NUM_RANDOM_STEPS=1
EXTERNAL_GENERATOR=$(echo "python3 $(pwd)/.tests/example_external.py" | base64 -w0)

if command -v nvidia-smi 2>/dev/null; then
	NUM_GPUS=1
fi

function help () {
	echo "Usage: $(basename "$0") [OPTIONS]"

	echo "Optional arguments:"
	echo "--mem_gb=<int>                   Memory in GB (default: 1)"
	echo "--time=<int>                     Time in minutes (default: 60)"
	echo "--worker_timeout=<int>           Timeout for worker (default: 60)"
	echo "--max_eval=<int>                 Maximum evaluations (default: 2)"
	echo "--num_parallel_jobs=<int>        Number of parallel jobs (default: 1)"
	echo "--gpus=<int>                     Number of GPUs (default: 1)"
	echo "--num_random_steps=<int>         Number of random steps (default: 1)"
	echo "--external_generator=<str>       External generator command (Base64 encoded)"
	echo "--help                           Show this help message and exit"
}

for arg in "$@"; do
  case $arg in
    --mem_gb=*) MEM_GB="${arg#*=}" ;;
    --time=*) TIME="${arg#*=}" ;;
    --worker_timeout=*) WORKER_TIMEOUT="${arg#*=}" ;;
    --max_eval=*) MAX_EVAL="${arg#*=}" ;;
    --num_parallel_jobs=*) NUM_PARALLEL_JOBS="${arg#*=}" ;;
    --gpus=*) NUM_GPUS="${arg#*=}" ;;
    --num_random_steps=*) NUM_RANDOM_STEPS="${arg#*=}" ;;
    --external_generator=*)
      RAW_GEN="${arg#*=}"
      EXTERNAL_GENERATOR=$(echo "$RAW_GEN" | base64 -w0)
      ;;
    --help) help; exit 0 ;;
    *) echo "Unknown option: $arg"; help; exit 1 ;;
  esac
done

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"
cd ..

./omniopt \
  --partition=alpha \
  --experiment_name=EXTERNAL_GENERATOR_test \
  --mem_gb="$MEM_GB" \
  --time="$TIME" \
  --worker_timeout="$WORKER_TIMEOUT" \
  --max_eval="$MAX_EVAL" \
  --num_parallel_jobs="$NUM_PARALLEL_JOBS" \
  --gpus="$NUM_GPUS" \
  --num_random_steps="$NUM_RANDOM_STEPS" \
  --follow \
  --live_share \
  --send_anonymized_usage_stats \
  --result_names RESULT=max \
  --run_program=ZWNobyAiUkVTVUxUOiAlKHgpJSh5KSIgJiYgZWNobyAiUkVTVUxUMjogJXoi \
  --cpus_per_task=1 \
  --nodes_per_job=1 \
  --generate_all_jobs_at_once \
  --revert_to_random_when_seemingly_exhausted \
  --model=EXTERNAL_GENERATOR \
  --run_mode=local \
  --occ_type=euclid \
  --main_process_gb=8 \
  --max_nr_of_zero_results=1 \
  --slurm_signal_delay_s=0 \
  --n_estimators_randomforest=100 \
  --parameter x range 123 100000000 int false \
  --parameter y choice 5431,1234 \
  --parameter z fixed 111 \
  --external_generator="$EXTERNAL_GENERATOR"

exit $?
