#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"

cd ..

NUM_GPUS=0

if command -v nvidia-smi 2>/dev/null; then
	NUM_GPUS=1
fi

./omniopt --partition=alpha --experiment_name=EXTERNAL_GENERATOR_with_constraints_test --mem_gb=1 --time=60 --worker_timeout=60 --max_eval=2 --num_parallel_jobs=1 --gpus=$NUM_GPUS --num_random_steps=1 --follow --live_share --send_anonymized_usage_stats --result_names RESULT=max --run_program=ZWNobyAiUkVTVUxUOiAlKHgpJSh5KSIgJiYgZWNobyAiUkVTVUxUMjogJXoi --cpus_per_task=1 --nodes_per_job=1 --generate_all_jobs_at_once --revert_to_random_when_seemingly_exhausted --model=EXTERNAL_GENERATOR --run_mode=local --occ_type=euclid --main_process_gb=8 --max_nr_of_zero_results=1 --slurm_signal_delay_s=0 --n_estimators_randomforest=100 --parameter x range 123 1000 int false --parameter y range 1234 4321 --parameter z range 111 222 int --external_generator $(echo "python3 $(pwd)/.tests/example_external.py" | base64 -w0) --experiment_constraint $(echo "x >= y" | base64 -w0) --seed 1234

exit_code=$?

exit $exit_code
