#!/usr/bin/env bash

# HELPPAGE: Finds typos in bash scripts.

export install_tests=1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .shellscript_functions
source .tests/helper_functions

if [[ -n $1 ]]; then
	python3 .tests/find_typos_in_bash.py $1
else
	files=$(grep -r "^#..usr.bin.env.bash" . 2>/dev/null | sed -e 's#:.*##')
	for filename in $files; do
		if file_has_changed_since_last_tagged_version "$filename"; then
			python3 .tests/find_typos_in_bash.py "$filename"
		fi
	done
fi
