#!/usr/bin/env bash

# HELPPAGE: Find functions that are defined in any .py and also .helpers.py, so that they can be moved to the .helpers.py compeletly.

count=0
for helper_function in $(cat .helpers.py | grep "^def " | sed -e 's#^def ##' -e 's#[[:space:]]*(.*##'); do
	for anything_but_helper in $(ls .*.py | grep -v helper); do
		if grep "def $helper_function[[:space:]]*(" "$anything_but_helper" 2>/dev/null >/dev/null; then
			echo "$helper_function exists in .helper.py and $anything_but_helper"
			count=$(($count+1))
		fi
	done
done

exit $count
