#!/usr/bin/env bash

# HELPPAGE: Finds typos in bash scripts.

export install_tests=1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .shellscript_functions
source .tests/helper_functions

if command -v python3 2>/dev/null >/dev/null; then
	if [[ -n $1 ]]; then
		python3 .tests/find_typos_in_bash.py "$@"
		exit_code=$?
	else
		files=""
		for filename in .*.py; do
			if file_has_changed_since_last_tagged_version "$filename"; then
				files="$files $filename"
			fi
		done

		if [[ -n "$files" ]]; then
			eval "python3 .tests/find_typos_in_bash.py $files"
			exit_code=$?
		else
			echo "No changed Python files to check."
			exit_code=0
		fi
	fi
else
	echo "Warning: python3 is not installed. Cannot run find_typos_in_bash"
fi
