#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

exceptions=(
	"receive_signal_cont"
	"convert_to_serializable"
	"custom_warning_handler"
	"receive_usr_signal"
	"live_share_background"
	"receive_usr_signal_int_or_term"
	"receive_usr_signal_int"
	"receive_usr_signal_term"
	"execute_nvidia_smi"
	"parse_choice_param"
	"parse_range_param"
	"parse_fixed_param"
	"_finish_previous_jobs_helper_wrapper"
)

unused_count=0

for funcname in $(grep "^def " .omniopt.py | sort | sed -e 's#^def[[:space:]]*##' -e 's#(.*##'); do
	if [[ " ${exceptions[@]} " =~ " $funcname " ]]; then
		continue
	fi

	cnt=$(grep -v "^def\s" .omniopt.py | grep "$funcname(" | grep -v is_equal | wc -l)

	if [[ $cnt -eq 0 ]]; then
		echo "$funcname: $cnt"
		((unused_count++))
	fi
done

exit $unused_count
