#!/usr/bin/env bash

# HELPPAGE: Find arguments in .omniopt.py that have double quotes and fail if they do, since other script that parse it need them to be single quotes.

function echoerr {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function green_text {
	echoerr -e "\033[0;32m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

double_quotes=$(cat .omniopt.py | grep "\.add_argument(\"")

double_quotes_nr=$(echo -ne "$double_quotes" | wc -l)

if [[ $double_quotes_nr -eq 0 ]]; then
	green_text "find_add_arguments_with_double_quotes OK"
	exit 0
fi

red_text "Error: found $double_quotes_nr double-quoted add_argument's:"
red_text "$double_quotes"

exit 1
