#!/usr/bin/env bash

# HELPPAGE: Check if all used exit codes are documented.

errors=0

for code in $(
		(
			grep -hPo 'my_exit\s*\(\s*\K\d+' omniopt .omniopt.py
			grep -hPo '_fatal_error\s*\(.*?,\s*\K\d+' omniopt .omniopt.py
		) | sort -n | uniq | grep -v '^0$'
	); do
	if ! grep -q "^[[:space:]]*$code =>" .gui/exit_code_table.php; then
		echo "Missing exit code: $code"
		errors=1
	fi
done

if [[ $errors -eq 1 ]]; then
	exit 1
fi
