#!/usr/bin/env bash

# HELPPAGE: Find help documentation files missing the Table-of-Contents.

function echoerr {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function green_text {
	echoerr -e "\033[0;32m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

errors=0

for missing_toc_file in $(find .gui/_tutorials/ -type f -name "*.md" -exec grep -L 'id="toc"' {} \; | xargs grep -l '^## '); do
	red_text "Missing TOC in $missing_toc_file"
	errors=$(($errors + 1))
done

if [[ $errors -eq 0 ]]; then
	green_text "find_missing_toc_in_md_files: No found"
	exit 0
fi

red_text "find_missing_toc_in_md_files: $errors found"
exit 0
