#!/usr/bin/env bash

function echoerr {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function green_text {
	echoerr -e "\033[0;32m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

IFS=$'\n'

errors=0

for cli_arg_line in $(cat .omniopt.py | grep "\.add_argument(" | sed -e 's#.*add_argument.##'); do
	_name=$(echo "$cli_arg_line" | sed -e "s#^'--##" -e "s#'.*##")
	_type=$(echo "$cli_arg_line" | sed -e 's#.*type=##' -e "s#\W.*##")
	_action=""
	_default=""
	_nargs=""

	if echo "$cli_arg_line" | grep -q "default="; then
		_default=$(echo "$cli_arg_line" | sed -e 's#.*default=##' -e "s#[,\W\)].*##")
		if [[ $_default == "True" ]] || [[ $_default == "False" ]]; then
			_type="bool"
		fi

		if [[ $_default == "None" ]]; then
			_type="Optional[$_type]"
		fi
	fi

	if echo "$cli_arg_line" | grep -q "nargs='"; then
		_nargs=$(echo "$cli_arg_line" | sed -e 's#.*nargs=##' -e "s#^'##" -e "s#'.*##")
	fi

	if echo "$cli_arg_line" | grep -q "action='"; then
		_action=$(echo "$cli_arg_line" | sed -e 's#.*action=##' -e "s#^'##" -e "s#'.*##")

		if [[ "$_action" == "append" ]]; then
			if [[ $_type == "Optional[]" ]] || [[ $_type -eq "str" ]]; then
				_type="Optional[List[str]]"
			fi
		fi
	fi

	if [[ "$_nargs" == "+" ]] || [[ "$_args" == "*" ]]; then
		if [[ $_type == "Optional[]" ]] || [[ $_type -eq "str" ]]; then
			_type="Optional[List[str]]"
		fi
	fi

	correctly_typed=1

	type_regex=$(echo "$_type" | sed -e 's/\[/\\[/g' -e 's/\]/\\]/g')

	if ! grep -Eq "^\s*$_name: $type_regex$" .omniopt.py; then
		if [[ "$_nargs" != "" ]]; then
			if [[ $_action != "" ]]; then
				red_text "Wrongly typed: $_name: $_type (nargs: $_nargs, action: $_action)"
			else
				red_text "Wrongly typed: $_name: $_type (nargs: $_nargs)"
			fi
		else
			if [[ $_action != "" ]]; then
				red_text "Wrongly typed: $_name: $_type (action: $_action)"
			else
				red_text "Wrongly typed: $_name: $_type"
			fi
		fi

		correctly_typed=0

		errors=$(($errors + 1))
	fi

	if [[ $correctly_typed != 1 ]]; then
		if [[ $_default != "" ]]; then
			echo "$_name: $_type, default: $_default"
		else
			echo "$_name: $_type"
		fi
	fi
done

if [[ $errors -eq 0 ]]; then
	green_text "find_wrongly_typed_cli_args: No errors found"
	exit 0
fi

red_text "find_wrongly_typed_cli_args: Found $errors errors"
exit 1
