#!/usr/bin/env bash

function echoerr {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function green_text {
	echoerr -e "\033[0;32m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

errs=0

for cli_arg in $(cat .omniopt.py | grep "\.add_argument(" | sed -e "s#',.*##" | sed -e "s#.*'##" | sed -e 's#^--##'); do
	if ! grep -Eq "^\s{4}${cli_arg}:" .omniopt.py; then
		red_text "$cli_arg has no type in ConfigLoader"
		errs=$(($errs+1))
	fi
done

if [[ $errs -eq 0 ]]; then
	green_text "find_untyped_cli_args: OK"
	exit 0
fi

echo "Failed find_untyped_cli_args: Found $errs errors"
exit 1
