#!/bin/bash

for install_type in omniopt git; do
	VENV_DIR=$HOME/omniopt_via_pip_$install_type/

	if [[ -d "$VENV_DIR" ]]; then
		rm -rf "$VENV_DIR"
	fi

	python3 -mvenv "$VENV_DIR"

	activate_file="$VENV_DIR/bin/activate"
	if [[ -e $activate_file ]]; then
		ok=1

		source $activate_file

		if [[ $install_type -eq "github" ]]; then
			pip install git+https://github.com/NormanTUD/OmniOpt/
		else
			pip install omniopt2
		fi

		omniopt --help
		exit_code=$?

		echo "omniopt --help exited with $exit_code"

		if [[ $exit_code -eq 0 ]]; then
			omniopt \
				--partition=alpha \
				--experiment_name=pip_test_experiment \
				--mem_gb=1 \
				--time=60 \
				--worker_timeout=60 \
				--max_eval=5 \
				--num_parallel_jobs=5 \
				--gpus=1 \
				--num_random_steps=2 \
				--follow \
				--send_anonymized_usage_stats \
				--result_names RESULT=min \
				--run_program='ZWNobyAiUkVTVUxUOiAlKHgpJSh5KSI=' \
				--cpus_per_task=1 \
				--nodes_per_job=1 \
				--generate_all_jobs_at_once \
				--model=BOTORCH_MODULAR \
				--run_mode=local \
				--decimalrounding=4 \
				--occ_type=euclid \
				--main_process_gb=8 \
				--max_nr_of_zero_results=50 \
				--pareto_front_confidence=1 \
				--slurm_signal_delay_s=0 \
				--parameter x range 123 100000000 int false \
				--parameter y range 5431 1234 float false
			exit_code=$?

			echo "omniopt-main-script exited with $exit_code"

			if [[ $exit_code -ne 0 ]]; then
				ok=0
			fi

			for to_check in omniopt_plot omniopt_docker omniopt_share omniopt_evaluate; do
				if ! which $to_check 2>/dev/null >/dev/null; then
					echo "$to_check not found"
					ok=0
				fi
			done
		else
			ok=0
		fi
	fi

	if [[ -d "$VENV_DIR" ]]; then
		rm -rf "$VENV_DIR"
	fi
done

if [[ $ok -eq 1 ]]; then
	exit 0
fi

exit 1
