#!/bin/bash

function echoerr() {
	echo "$@" 1>&2
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

function green_text {
	echoerr -e "\e\033[0;32m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

cd .gui

if ! command -v node 2>/dev/null >/dev/null; then
	echo "node not installed! Will skip JS testing."
	exit 0
fi

node gui_js_tests.js
exit_code=$?

if [[ $exit_code != 0 ]]; then
	red_text "At least one JS-unit test failed"
	exit 1
else
	if [[ -n ${SHOW_SUCCESS} ]]; then
		green_text "JS-Unit-Tests OK"
	fi

	exit 0
fi
