#!/usr/bin/env bash

# HELPPAGE: Test scripts for cyclomatic complexity.

export install_tests=1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .shellscript_functions

exit_code=0

if command -v lizard 2>/dev/null >/dev/null; then
	STD=$(lizard .*.py 2>&1)
	exit_code=$?

	if [[ $exit_code -ne 0 ]]; then
		echo "$STD"
	else
		echo "Lizard: OK"
	fi
else
	echo "Warning: lizard is not installed. Cannot run lizard"
fi

exit $exit_code
