#!/usr/bin/env bash

# HELPPAGE: Find environment variables that change how OmniOpt works that are not documented.

function echoerr {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function green_text {
	echoerr -e "\033[0;32m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

err=0

for i in $(ls .omniopt_plot_*.py); do
	if ! grep -q "dark" $i; then
		red_text "Missing dark mode in $i"
		err=1
	fi
done

if [[ $err -eq 1 ]]; then
	red_text "Missing dark mode for at least one plot"
	exit 1
fi

exit 0
