site_name: OmniOpt2
docs_dir: "../.gui/_tutorials"
theme:
  name: "mkdocs"
markdown_extensions:
  - codehilite
  - pymdownx.superfences  # Add this line
  - toc:
      permalink: true
plugins:
  - code-validator:
      enabled: true
      identifiers:
        bash:
          command: 'bash -n'
        python:
          command: 'python -m py_compile'
        json:
          command: 'python -m json.tool'
