#!/usr/bin/env bash

function echoerr {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function green_text {
	echoerr -e "\033[0;32m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..



NUM_GPUS=0

if command -v nvidia-smi 2>/dev/null >/dev/null; then
	NUM_GPUS=1
fi

./omniopt --partition=alpha --experiment_name=multiplication_constraint --mem_gb=10 --time=60 --worker_timeout=60 --max_eval=4 --num_parallel_jobs=4 --gpus=$NUM_GPUS --num_random_steps=2 --follow --live_share --send_anonymized_usage_stats --result_names RESULT=min --run_program='cGVybCAtZSAncHJpbnQgIlJFU1VMVDogIiAuICglYSArICViKSc=' --cpus_per_task=1 --nodes_per_job=1 --generate_all_jobs_at_once --revert_to_random_when_seemingly_exhausted --model=BOTORCH_MODULAR --n_estimators_randomforest=100 --run_mode=local --decimalrounding=4 --occ_type=euclid --main_process_gb=8 --max_nr_of_zero_results=50 --slurm_signal_delay_s=0 --max_failed_jobs=0 --parameter a range 0 100 float false --parameter b range 0 100 float false --experiment_constraints 'YSAqIGIgPj0gMTA='

exit_code=$?

if [[ $exit_code -eq 0 ]]; then
	green_text "Test multiplication_constraint OK"
	exit 0
fi

red_text "Test multiplication_constraint failed. Exit-Code: $exit_code"
exit 1
