#!/usr/bin/env bash

# HELPPAGE: Run mypy to find variables that are not typed properly.

export install_tests=1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .shellscript_functions

exit_code=0

if ! command -v mypy 2>/dev/null >/dev/null; then
	pip install -q mypy types-PyYAML types-toml
fi

if command -v mypy 2>/dev/null >/dev/null; then
	if [[ -z $1 ]]; then
		mypy --check-untyped-defs --ignore-missing-imports --disallow-untyped-defs .*.py
		exit_code=$?
	else
		mypy --check-untyped-defs --ignore-missing-imports --disallow-untyped-defs $*
		exit_code=$?
	fi
else
	echo "Warning: mypy is not installed. Cannot run mypy"
fi

exit $exit_code
