#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

cd .gui

if ! command -v php 2>/dev/null >/dev/null; then
	echo "php not installed! Will skip testing."
	exit 0
fi

export IS_RUNNING_UNIT_TESTS=1

php tests.php
exit_code=$?

if [[ $exit_code != 0 ]]; then
	echo "Test failed!!!"
	exit 1
fi

exit 0
