#!/bin/bash

function echoerr() {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

function green_text {
	echoerr -e "\e\033[0;32m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

cd .gui

if ! command -v php 2>/dev/null >/dev/null; then
	echo "php not installed! Will skip testing."
	exit 0
fi

export IS_RUNNING_UNIT_TESTS=1

php tests.php
exit_code=$?

if [[ $exit_code != 0 ]]; then
	red_text "At least one PHP-unit test failed Test failed"
	exit 1
else
	green_text "PHP-Unit-Tests OK"
	exit 0
fi
