#!/usr/bin/env bash

export install_tests=1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"

cd ..

if [[ ! -e .shellscript_functions ]]; then
	echo ".shellscript_functions not found. Cannot continue."
	exit 1
fi

source .shellscript_functions

res=$(pymarkdown scan .gui/_tutorials/*.md | grep -iv "Line length" | grep -v "Hard tabs" | grep -v "Inline HTML" | grep -v "Fenced code blocks should have a language specified" | grep -v "^\s*$")

echo "$res"

nr_lines=$(echo "$res" | wc -l)

exit $nr_lines
