#!/bin/bash

export install_tests=1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"

cd ..

if [[ ! -e .shellscript_functions ]]; then
	echo ".shellscript_functions not found. Cannot continue."
	exit 1
fi

source .shellscript_functions

mkdocs build --strict -f .tests/mkdocs.yml
