#!/usr/bin/env bash

# HELPPAGE: In OmniOpt, there is a parser that allows to parse argparse-like arguments before python. This tests it's output
#
function echoerr() {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

function green_text {
	echoerr -e "\e\033[0;32m$1\e[0m"
}

export DEBUG_PARAM_EVAL=1
export DONT_SHOW_STARTUP_COMMAND=1

.tests/start_simple_optimization_run --num_parallel_jobs=2 --gpus=0 --num_random_steps=1 --max_eval=1 --mem_gb=1 --generate_all_jobs_at_once --follow


exit_code=$?

if [[ $exit_code -eq 222 ]]; then
	green_text "Test test_bash_argparse_clone OK"
else
	red_text "Test test_bash_argparse_clone failed"
	exit 1
fi

exit 0
