#!/usr/bin/env bash

function echoerr() {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

function green_text {
	echoerr -e "\e\033[0;32m$1\e[0m"
}

export DEBUG_PARAM_EVAL=1

.tests/start_simple_optimization_run --num_parallel_jobs=2 --gpus=0 --num_random_steps=1 --max_eval=1 --mem_gb=1 --generate_all_jobs_at_once --follow --debug


exit_code=$?

if [[ $exit_code -eq 0 ]]; then
	green_text "Test test_bash_argparse_clone OK"
else
	green_text "Test test_bash_argparse_clone failed"
fi

exit $exit_code
