#!/usr/bin/env bash

# HELPPAGE: Starts an OmniOpt2 run that trains an example neural network.

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

if [[ -z $OMNIOPT_CALL ]]; then
	OMNIOPT_CALL="./omniopt"
fi
export OMNIOPT_CALL

function set_debug {
	trap 'echo -e "${CYAN}$(date +"%Y-%m-%d %H:%M:%S")${NC} ${MAGENTA}| Line: $LINENO ${NC}${YELLOW}-> ${NC}${BLUE}[DEBUG]${NC} ${GREEN}$BASH_COMMAND${NC}"' DEBUG
}

function unset_debug {
	trap - DEBUG
}

export OO_MAIN_TESTS=1

function echoerr() {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

function green_text {
	echoerr -e "\e\033[0;32m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

function echoerr() {
	echo "$@" 1>&2
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

set -e
set -o pipefail

function calltracer () {
	yellow_text "Git status hash:"
	git rev-parse HEAD
	red_text 'Error occurred in file/line:'
	caller
}

trap 'calltracer' ERR

export max_eval=200
export num_parallel_jobs=20
export worker_timeout=30
export mem_gb=5
export runtime=300
export min_epochs=10
export max_epochs=40
export min_dense=1
export max_dense=10
export data=data_tiny

export min_conv=1
export max_conv=10

export min_conv_filters=1
export max_conv_filters=10

export min_dense_units=1
export max_dense_units=10

export min_height=40
export max_height=80
export min_width=40
export max_width=80

export follow=0
export gridsearch=0
export num_random_steps=$num_parallel_jobs
export validation_split=0.2

export min_learning_rate=0.001
export max_learning_rate=0.4

export generate_all_jobs_at_once=0
export revert_to_random_when_seemingly_exhausted=0
export result_names=()

function help () {
	echo "train_example_network: Trains an example network from asanAI for testing OmniOpt2"
	echo "Possible options:"
	echo "  --help                                                 This help"
	echo "  --debug                                                Enables debug mode"
	echo "  --data=<str>                                           Data folder (default: data, possible options: data_tiny)"
	echo "  --num_parallel_jobs=<int>                              Number of parallel jobs (default: 20, but at least --num_random_steps)"
	echo "  --worker_timeout=<int>                                 Number of minutes for a single-worker to timeout (default: 30)"
	echo "  --mem_gb=<int>                                         Memory in GB (default 5)"
	echo "  --time=<int>                                           Max runtime in minutes (default: 300)"
	echo "  --num_random_steps=<int>                               Number of random steps"
	echo "  --max_eval=<int>                                       Max number of evals (default: 200)"
	echo "  --min_dense=<int>                                      Number of min dense layers (default: 1)"
	echo "  --max_dense=<int>                                      Number of max dense (default: 10)"
	echo "  --min_dense_units=<int>                                Number of min dense_units layers (default: 1)"
	echo "  --max_dense_units=<int>                                Number of max dense_units (default: 10)"
	echo "  --min_conv_filters=<int>                               Number of min conv_filters layers (default: 1)"
	echo "  --max_conv_filters=<int>                               Number of max conv_filters (default: 10)"
	echo "  --min_conv=<int>                                       Number of min conv layers (default: 1)"
	echo "  --max_conv=<int>                                       Number of max conv (default: 10)"
	echo "  --min_epochs=<int>                                     Number of min epochs (default: 10)"
	echo "  --max_epochs=<int>                                     Number of max epochs (default: 40)"
	echo "  --min_height=<int>                                     Min height (default: 40)"
	echo "  --max_height=<int>                                     max height (default: 80)"
	echo "  --min_width=<int>                                      Min width (default: 40)"
	echo "  --max_width=<int>                                      max width (default: 80)"
	echo "  --min_learning_rate=<float>                            Min learning_rate (default: 0.01)"
	echo "  --max_learning_rate=<float>                            Max learning_rate (default: 0.4)"
	echo "  --validation_split=<float>                             Validation split (default: 0.2)"
	echo "  --result_names=<str>                                   Result names (default: VAL_ACCURACY=max VAL_LOSS=min RAM_USAGE=min RUNTIME=min)"
	echo "  --follow                                               Follow the output (default: 0)"
	echo "  --gridsearch                                           Do gridsearch"
	echo "  --generate_all_jobs_at_once                            Generate all jobs at once"
	echo "  --revert_to_random_when_seemingly_exhausted            Revert to random search when search space seems exhausted"
	exit $1
}

iarray_to_string() {
    echo "$*"
}

function join_by {
	local d=${1-} f=${2-}
	if shift 2; then
		printf %s "$f" "${@/#/$d}"
	fi
}

int_re='^[+-]?[0-9]+$'

args=("$@")

for i in "$@"; do
	case $i in
		--num_random_steps=*)
			num_random_steps="${i#*=}"
			if ! [[ $num_random_steps =~ $int_re ]] ; then
				red_text "error: --num_random_steps not a INT: $i" >&2
				exit 100
			fi

			;;
		--num_random_steps)
			shift
			k=$((k+1))

			num_random_steps="${args[k]}"
			if ! [[ $num_random_steps =~ $int_re ]] ; then
				red_text "error: --num_random_steps not a INT: $i" >&2
				exit 100
			fi

			;;
		--data=*)
			data="${i#*=}"
			shift
			;;
		--mem_gb=*)
			mem_gb="${i#*=}"
			shift
			;;
		--worker_timeout=*)
			worker_timeout="${i#*=}"
			shift
			;;
		--num_parallel_jobs=*)
			num_parallel_jobs="${i#*=}"
			shift
			;;
		--time=*)
			runtime="${i#*=}"
			shift
			;;


		--min_conv=*)
			min_conv="${i#*=}"
			shift
			;;
		--max_conv=*)
			max_conv="${i#*=}"
			shift
			;;

		--min_conv_filters=*)
			min_conv_filters="${i#*=}"
			shift
			;;
		--max_conv_filters=*)
			max_conv_filters="${i#*=}"
			shift
			;;

		--min_dense_units=*)
			min_dense_units="${i#*=}"
			shift
			;;
		--max_dense_units=*)
			max_dense_units="${i#*=}"
			shift
			;;

		--min_height=*)
			min_height="${i#*=}"
			shift
			;;
		--max_height=*)
			max_height="${i#*=}"
			shift
			;;

		--min_width=*)
			min_width="${i#*=}"
			shift
			;;
		--max_width=*)
			max_width="${i#*=}"
			shift
			;;

		--min_dense=*)
			min_dense="${i#*=}"
			shift
			;;
		--max_dense=*)
			max_dense="${i#*=}"
			shift
			;;

		--min_epochs=*)
			min_epochs="${i#*=}"
			shift
			;;
		--max_epochs=*)
			max_epochs="${i#*=}"
			shift
			;;

		--min_learning_rate=*)
			min_learning_rate="${i#*=}"
			shift
			;;
		--max_learning_rate=*)
			max_learning_rate="${i#*=}"
			shift
			;;

		--validation_split=*)
			validation_split="${i#*=}"
			shift
			;;
		--max_eval=*)
			max_eval="${i#*=}"
			shift
			;;
		--gridsearch)
			gridsearch=1
			shift
			;;
		--follow)
			follow=1
			shift
			;;

		--result_names=*)
			result_names+=("${i#*=}")
			shift
			;;

		-h|--help)
			help 0
			;;
		--generate_all_jobs_at_once)
			generate_all_jobs_at_once=1
			;;
		--revert_to_random_when_seemingly_exhausted)
			revert_to_random_when_seemingly_exhausted=1
			;;
		--debug)
			set_debug
			;;
		*)
			red_text "Unknown parameter $i" >&2
			help 1
			;;
	esac
done

if [ -z "$result_names" ]; then
	result_names="VAL_ACCURACY=max VAL_LOSS=min RAM_USAGE=min RUNTIME=min"
fi

PARTITION="alpha"
NUM_GPUS=0

if command -v nvidia-smi 2>/dev/null >/dev/null; then
	NUM_GPUS=$(nvidia-smi --list-gpus | wc -l)
fi

if [[ "$NUM_GPUS" -ne "0" ]]; then
	NUM_GPUS=1
fi

cd ..

yellow_text "Installing modules..."

bash .tests/example_network/install.sh

yellow_text "Done installing modules"

#if [[ -d runs/example_network/ ]]; then
#	rm -rf runs/example_network/
#fi

exit_code=0

function generate_parameter {
	local name="$1"
	local min_value="$2"
	local max_value="$3"
	local type="$4"

	if [[ "$min_value" == "$max_value" ]]; then
		echo "--parameter $name fixed $min_value"
	else
		echo "--parameter $name range $min_value $max_value $type"
	fi
}


cmd="$OMNIOPT_CALL --live_share --send_anonymized_usage_stats \
	--partition=$PARTITION \
	--experiment_name=example_network \
	--mem_gb=$mem_gb \
	--time=$runtime \
	--worker_timeout=$worker_timeout \
	--max_eval=$max_eval \
	--num_parallel_jobs=$num_parallel_jobs \
	--gpus=$NUM_GPUS \
	--run_program=$(echo "bash $SCRIPT_DIR/example_network/run.sh --learning_rate=%(learning_rate) --epochs=%(epochs) --validation_split=$validation_split --width=%(width) --height=%(height) --dense=%(dense) --dense_units=%(dense_units) --conv=%(conv) --conv_filters=%(conv_filters) --data=$data --activation=%(activation)" | base64 -w 0) \
	$(generate_parameter width $min_width $max_width int) \
	$(generate_parameter height $min_height $max_height int) \
	$(generate_parameter dense $min_dense $max_dense int) \
	$(generate_parameter dense_units $min_dense_units $max_dense_units int) \
	$(generate_parameter epochs $min_epochs $max_epochs int) \
	$(generate_parameter conv $min_conv $max_conv int) \
	$(generate_parameter conv_filters $min_conv_filters $max_conv_filters int) \
	$(generate_parameter learning_rate $min_learning_rate $max_learning_rate float) \
	--parameter activation choice relu,sigmoid,swish,leaky_relu,tanh,gelu \
	--result_names $(iarray_to_string "${result_names[@]}") \
	--num_random_steps=$num_random_steps"

if [[ "$gridsearch" -eq "1" ]]; then
	cmd="$cmd --gridsearch"
	experiment_name="example_network_gridsearch"
else
	experiment_name="example_network"
fi

if [[ $generate_all_jobs_at_once -eq 1 ]]; then
	cmd="$cmd --generate_all_jobs_at_once"
fi

if [[ $revert_to_random_when_seemingly_exhausted -eq 1 ]]; then
	cmd="$cmd --revert_to_random_when_seemingly_exhausted"
fi

cmd=$(echo "$cmd" | sed "s/--experiment_name=example_network/--experiment_name=$experiment_name/")

if [[ "$follow" -eq "1" ]]; then
	cmd+=" --follow"
fi

eval "$cmd"

exit $exit_code
