#!/bin/bash

python3.7 /home/h8/s3811141/test/randomtest_40254/omniopt/script/hyperopt-mongo-worker --reserve-timeout=3600 --max-consecutive-failures=10000 --mongo=172.24.148.20:58029/gpu_test --poll-interval=10.0 --last-job-timeout=500 --workdir=/home/h8/s3811141/test/randomtest_40254/omniopt/test/projects/gpu_test --max-jobs=4

rm /home/h8/s3811141/test/randomtest_40254/omniopt/test/projects/gpu_test/worker_start_command

