#!/bin/bash

python3.7 /home/h8/s3811141/test/randomtest_40254/omniopt/script/hyperopt-mongo-worker --reserve-timeout=3600 --max-consecutive-failures=10000 --mongo=172.24.140.157:52610/cpu_test2 --poll-interval=10.0 --last-job-timeout=500 --workdir=/home/h8/s3811141/test/randomtest_40254/omniopt/test/projects/cpu_test2 --max-jobs=10

rm /home/h8/s3811141/test/randomtest_40254/omniopt/test/projects/cpu_test2/worker_start_command

