services:
  slurm-frontend:
    image: ghcr.io/normantud/omniopt/slurm_docker/slurm_docker_slurmfrontend:latest
    container_name: slurm-frontend
    hostname: slurm-frontend
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmmaster:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmmasteratest:latest
    container_name: slurmmaster
    hostname: slurmmaster
    depends_on:
      - slurm-frontend
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmnode1:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmnode1atest:latest
    container_name: slurm-node1
    hostname: slurm-node1
    depends_on:
      - slurmmaster
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmnode2:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmnode2atest:latest
    container_name: slurm-node2
    hostname: slurm-node2
    depends_on:
      - slurmmaster
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmnode3:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmnode3atest:latest
    container_name: slurm-node3
    hostname: slurm-node3
    depends_on:
      - slurmmaster
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmnode4:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmnode4atest:latest
    container_name: slurm-node4
    hostname: slurm-node4
    depends_on:
      - slurmmaster
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

networks:
  slurmnet:
    driver: bridge
