services:
  slurm-frontend:
    image: ghcr.io/normantud/omniopt/slurm_docker/slurm_docker_slurmfrontend:latest
    container_name: slurm-frontend
    hostname: slurm-frontend
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmmaster:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmmasteratest:latest
    container_name: slurmmaster
    hostname: slurmmaster
    depends_on:
      - slurm-frontend
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmnode1:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmnode1atest:latest
    container_name: slurmnode1
    hostname: slurmnode1
    depends_on:
      - slurmmaster
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmnode2:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmnode2atest:latest
    container_name: slurmnode2
    hostname: slurmnode2
    depends_on:
      - slurmmaster
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmnode3:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmnode3atest:latest
    container_name: slurmnode3
    hostname: slurmnode3
    depends_on:
      - slurmmaster
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

  slurmnode4:
    image: ghcr.io/normantud/omniopt/slurm_docker_slurmnode4atest:latest
    container_name: slurmnode4
    hostname: slurmnode4
    depends_on:
      - slurmmaster
    restart: unless-stopped
    volumes:
      - ../../:/oo_dir
    networks:
      - slurmnet

networks:
  slurmnet:
    driver: bridge
