services:
  slurmfrontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        container_name: slurm-frontend
        shm_size: '4g'
        hostname: slurmfrontend
        user: admin
        volumes:
                - shared-vol:/home/admin
                - ../../:/oo_dir
        ports:
                - 8888:8888
  slurm-master:
        build:
          context: ./master
          dockerfile: Dockerfile
        container_name: slurm-master
        shm_size: '4g'
        hostname: slurm-master
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
                - ../../:/oo_dir
        environment:
                - SLURM_CPUS_ON_NODE=1
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819


  slurmnode1:
        build:
          context: ./node
          dockerfile: Dockerfile
        container_name: slurm-node1
        shm_size: '4g'
        hostname: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
                - ../../:/oo_dir
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurm-master

  slurmnode2:
        build:
          context: ./node
          dockerfile: Dockerfile
        container_name: slurm-node2
        shm_size: '4g'
        hostname: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
                - ../../:/oo_dir
        environment:
                - SLURM_NODENAME=slurmnode2
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurm-master

  slurmnode3:
        build:
          context: ./node
          dockerfile: Dockerfile
        container_name: slurm-node3
        shm_size: '4g'
        hostname: slurmnode3
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
                - ../../:/oo_dir
        environment:
                - SLURM_NODENAME=slurmnode3
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurm-master

  slurmnode4:
        build:
          context: ./node
          dockerfile: Dockerfile
        container_name: slurm-node4
        shm_size: '4g'
        hostname: slurmnode4
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
                - ../../:/oo_dir
        environment:
                - SLURM_NODENAME=slurmnode4
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurm-master


volumes:
        shared-vol:
