#!/bin/bash

set -euo pipefail

DEFAULT_BASE_URL="https://imageseg.scads.de/omniax/"
BASE_URL_FILE="$HOME/.oo_base_url"

if [ -f "$BASE_URL_FILE" ]; then
	BASE_URL=$(cat "$BASE_URL_FILE")
else
	BASE_URL="$DEFAULT_BASE_URL"
fi

SHARES_DIR="shares"
SHARE_BEFORE=0
USERNAME="$USER"

FILTER_USER=""
FILTER_EXPERIMENT=""
EXPORT_DIR=""

function help {
	echo "Usage: $0 --export_dir <path> [--user <username>] [--experiment <experiment>]"
	echo ""
	echo "Options:"
	echo "  --user           Optional: Filter by user"
	echo "  --experiment     Optional: Filter by experiment"
	echo "  --autosubmit     Optional: Auto submit each job in runs before trying to export"
	echo "  --username       Optional: Name of the user if it should be submitted, defaults to $USER"
	echo "  --export_dir     Required: Directory to save exported HTML files"
	echo "  -h, --help       Show this help message"
	echo ""
	echo "Example:"
	echo "  $0 --username alice --experiment test_exp --export_dir ./exports"
	exit 0
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		--autosubmit)
			SHARE_BEFORE=1
			shift 1
			;;
		--user)
			FILTER_USER="$2"
			shift 2
			;;
		--experiment)
			FILTER_EXPERIMENT="$2"
			shift 2
			;;
		--username)
			USERNAME="$2"
			shift 2
			;;
		--export_dir)
			EXPORT_DIR="$2"
			shift 2
			;;
                -h|--help)
                        help
                        ;;
                *)
                        echo "Unknown argument: $1"
                        help
                        ;;
	esac
done


if [[ $SHARE_BEFORE -eq 1 ]]; then
	cd ..
	BASE_DIR="runs"
	find "$BASE_DIR" -type f -name "results.csv" | while read -r csv_path; do
		dir_path="$(dirname "$csv_path")"

		bash omniopt_share --username="$USERNAME" "$dir_path"
	done
	cd -
fi

if [[ "$EXPORT_DIR" == "" ]]; then
	echo "--export_dir must be set"
	exit 1
fi

if [ ! -d "$SHARES_DIR" ]; then
	echo "Directory '$SHARES_DIR' does not exist."
	exit 2
fi

find "$SHARES_DIR" -mindepth 3 -maxdepth 3 -type d | while read -r RUN_DIR; do
	USER=$(echo "$RUN_DIR" | cut -d'/' -f2)
	EXPERIMENT=$(echo "$RUN_DIR" | cut -d'/' -f3)
	RUN_NR=$(basename "$RUN_DIR")

	if ! [[ "$RUN_NR" =~ ^[0-9]+$ ]]; then
		continue
	fi

	if [ -n "$FILTER_USER" ] && [ "$USER" != "$FILTER_USER" ]; then
		continue
	fi

	if [ -n "$FILTER_EXPERIMENT" ] && [ "$EXPERIMENT" != "$FILTER_EXPERIMENT" ]; then
		continue
	fi

	URL="${BASE_URL%/}/share?&user_id=${USER}&experiment_name=${EXPERIMENT}&sort=time_desc&run_nr=${RUN_NR}&export_and_exit=1"

	export_to="$EXPORT_DIR/${USER}_${EXPERIMENT}_${RUN_NR}.html"

	mkdir -p $EXPORT_DIR || {
		echo "Error creating $EXPORT_DIR"
		exit 3
	}

	html=$(curl -fsSL "$URL" || echo "Request failed for: $URL")
	exit_code=$?

	if [[ $exit_code -eq 0 ]]; then
		echo "$html" > $export_to
		echo "Exported to $export_to"
	else
		echo "$html"
	fi
done
