#!/bin/bash

python3.7 /home/h8/s3811141/test/randomtest_77962/omniopt/script/hyperopt-mongo-worker --reserve-timeout=3600 --max-consecutive-failures=10000 --mongo=172.24.139.112:18516/gridsearch --poll-interval=10.0 --last-job-timeout=500 --workdir=/home/h8/s3811141/test/randomtest_77962/omniopt/test/projects/gridsearch --max-jobs=100

rm /home/h8/s3811141/test/randomtest_77962/omniopt/test/projects/gridsearch/worker_start_command

