#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

for i in $(grep -ri '#!/bin/bash' | sed -e 's#:.*##' | sort | grep -v "^omniopt$"); do
	if echo "$(file $i)" | grep "Bourne" 2>/dev/null >/dev/null; then
		if cat $i | grep -- "--help" 2>/dev/null >/dev/null; then
			bashscript_that_has_help="$i"

			echo "$bashscript_that_has_help"
			$bashscript_that_has_help --help
		fi
	fi
done
