#!/bin/bash

function join_by {
	local d=${1-} f=${2-}
	if shift 2; then
		printf %s "$f" "${@/#/$d}"
	fi
}

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

for i in $(grep -ri '#!/bin/bash' | sed -e 's#:.*##' | sort | grep -v "^omniopt$"); do
	if echo "$(file $i)" | grep "Bourne" 2>/dev/null >/dev/null; then
		if cat $i | grep -- "--help" 2>/dev/null >/dev/null; then
			bashscript_that_has_help="$i"

			echo "$bashscript_that_has_help"
			bash $bashscript_that_has_help --help

			exit_code=$?

			if [[ $exit_code != 0 ]]; then
				red_text "bash $bashscript_that_has_help --help failed with exit-code $exit_code"
			fi
		fi
	fi
done
