#!/bin/bash

params=(
	"--experiment_name=small_test_experiment"
	"--max_eval=2"
	"--num_parallel_jobs=1"
	"--num_random_steps=1"
	"--run_program='ZWNobyAiUkVTVUxUOiAlKHgpJSh5KSI='"
	"--result_names result"
	"--parameter x range 123 100000000 int false"
	"--parameter y range 5431 1234 float false"
)

num_params=${#params[@]}
total_combinations=$((2**num_params - 1))

echo "total_combinations: $total_combinations" >&2

for ((i = 1; i <= total_combinations; i++)); do
	echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
	cmd="./omniopt"

	for ((j = 0; j < num_params; j++)); do
		if (( (i >> j) & 1 )); then
			cmd+=" ${params[j]}"
		fi
	done

	echo "$cmd"

	$cmd

	_ec=$?

	echo "Exit-code: $_ec"

	echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
done
