#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .shellscript_functions

exit_code=0

if command -v php 2>/dev/null >/dev/null; then
	python3 .tools/php_spellchecker.py .gui/
	exit_code=$?
else
	echo "Warning: PHP is not installed. Cannot run php_spellchecker"
fi

exit $exit_code
