#!/bin/bash

export install_tests=1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .shellscript_functions

if [[ -n $1 ]]; then
	python3 .tests/find_typos_in_js.py $*
else
	files=$(ls .gui/*.js | grep -v tex-mml-chtml.js | grep -v jquery | grep -v d3 | grep -v ansi_up | grep -v "crypto-core" | grep -v plotly | grep -v tooltipster | tr '\n' ' ')
	eval "python3 .tests/find_typos_in_js.py $files"
fi
