#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR
cd ..

exclude=(
	"main"
	"parse_arguments"
	"plot_graph"
	"plot_graphs"
	"use_matplotlib"
	"update_graph"
	"get_args"
	"plot_single_graph"
	"print_debug"
	"filter_data"
	"plot_multiple_graphs"
	"set_margins"
)

declare -A function_files

for i in .*.py; do
	functions=$(grep -oP "^def\s+\K\w+" "$i")

	while IFS= read -r function; do
		if [[ ! " ${exclude[@]} " =~ " ${function} " ]]; then
			function_files["$function"]+="$i "
		fi
	done <<< "$functions"
done

echo -e "Functions that appear in multiple files:"
for function in "${!function_files[@]}"; do
	files=(${function_files[$function]})
	if [ "${#files[@]}" -gt 1 ]; then
		echo "$function: ${function_files[$function]}"
	fi
done
