#!/bin/bash

function echoerr {
	echo "$@" 1>&2
}

function yellow_text {
	echoerr -e "\e\033[0;33m$1\e[0m"
}

function green_text {
	echoerr -e "\033[0;32m$1\e[0m"
}

function red_text {
	echoerr -e "\e[31m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

cd .gui

FOUND_FUNCS=$(grep "^function " *.js | grep -v jquery | sed -e 's#.*function\s\s*##' -e 's#\s*(.*##' | sort | uniq -d) # )

if [ -z "$FOUND_FUNCS" ]; then
	FOUND_NR=0
else
	FOUND_NR=$(echo "$FOUND_FUNCS" | wc -l)
fi

if [[ $FOUND_NR -eq 0 ]]; then
	green_text "Found no double defined functions"
	exit 0
else
	red_text "Found $FOUND_NR double defined functions:"
	red_text "$FOUND_FUNCS"
	exit 1
fi
