#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .shellscript_functions

if [[ -n $1 ]]; then
	python3 .tests/find_typos_in_php.py $1
else
	files=$(ls .gui/*.php .gui/*/*.php | grep -v jquery | grep -v plotly | grep -v tooltipster | tr '\n' ' ')
	eval "python3 .tests/find_typos_in_php.py $files"
fi
