#!/bin/bash

unused_params=0

for each in $(
	for arg in $(cat .omniopt.py | grep "add_argument" | grep - "--" | sed -e "s#.*['\"]--##" -e "s#[\"'],.*##" | egrep "^\w*$"); do
		cnt=$(cat .omniopt.py | grep "args.$arg" | wc -l)
		echo "$cnt: $arg"
	done | sort -nr | grep "^0:" | grep -v "workdir" | grep -v "show_ram_every_n_seconds" | grep -v "partition" | grep -v "checkout_to_latest_tested_version" | \
		grep "send_anonymized_usage_stats" | grep -v "run_mode" | grep -v "send_anonymized_usage_stats"
	); do
	unused_params=$((unused_params+1))
done

echo "Unused params: $unused_params"
exit $unused_params
