#!/bin/bash

errors=()

function join_by {
	local d=${1-} f=${2-}
	if shift 2; then
		printf %s "$f" "${@/#/$d}"
	fi
}

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

expected_plot_types=()

CURRENT_HELP=$(./omniopt --help)
CLEANED_HELP=$(echo $CURRENT_HELP | sed -e 's#Usage: omniopt\s*##' -e 's#Example:...omniopt.*##' | sed -e 's#\[##g' -e 's#\]##g' | sed -e 's#\s#\n#g' | grep -- "--" | egrep -v -- '^\s*--\s*$' | sort | uniq)
echo $CLEANED_HELP

for help_param in $CLEANED_HELP; do
	set -x
	if ! grep "<tt>$help_param.*</tt>" .gui/help.php 2>&1 >/dev/null; then
		errmsg="Help parameter $help_param does not appear in .gui/help.php"
		red_text "$errmsg"
		errors+=("$errmsg")
	fi
done

secs=$SECONDS
hrs=$(( secs/3600 )); mins=$(( (secs-hrs*3600)/60 )); secs=$(( secs-hrs*3600-mins*60 ))
printf 'help_page test took: %02d:%02d:%02d\n' $hrs $mins $secs

if [ ${#errors[@]} -eq 0 ]; then
	green_text "No plot errors"
	exit 0
else
	red_text "=> PLOT-ERRORS => PLOT-ERRORS => PLOT-ERRORS =>"
	for i in "${errors[@]}"; do
		red_text "$i"
	done

	exit ${#errors[@]}
fi
