#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .shellscript_functions

exit_code=0

if command -v mypy 2>/dev/null >/dev/null; then
	if [[ -z $1 ]]; then
		for i in .*.py; do
			mypy --check-untyped-defs --ignore-missing-imports $i
		done
	else
		mypy --check-untyped-defs --ignore-missing-imports $*
		exit_code=$?
	fi
else
	echo "Warning: mypy is not installed. Cannot run mypy"
fi

exit $exit_code
