#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

ERRORS=()

if command -v php 2>/dev/null >/dev/null; then
	php .gui/test_share_functions.php
	exit_code=$?

	if [[ $exit_code -ne 0 ]]; then
		error_msg="php .gui/test_share_functions.php failed with exit-code $exit_code"
		red_text "$error_msg"
		ERRORS+=("$error_msg")
	fi
else
	yellow_text "Cannot run php_search-test when PHP is not installed!"
	exit 255
fi

exit ${#ERRORS[@]}
