#!/bin/bash

export disable_folder_creation=1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

cd .gui

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

if ! command -v php 2>/dev/null >/dev/null; then
	yellow_text "Cannot run share-test when PHP is not installed!"
	exit 255
fi

ERRORS=()

export share_path=./_share_test_case/

#php_share_internal_startpage=$(php share_internal.php | sed -e 's#<!--\s*[^-]*\s*-->##g' -e 's#^\s*##' | grep -v '^\s*$' | tr '\n' ' ' | sed -e 's#\s\s*# #g' -e 's#\s*$##' -e 's#^\s##' 2>&1)
#expected_share_internal_startpage="Using sharesPath ./_share_test_case/ <script src='plotly-latest.min.js'></script> <script src='share.js'></script> <script src='share_graphs.js'></script> <link href=\"./share.css\" rel=\"stylesheet\" /> <div id=\"breadcrumb\"></div> <a class='_share_link' href=\"share.php?user_id=test_user&share_path=./_share_test_case/\">test_user</a><br> <script>createBreadcrumb('./');</script>"
#if [[ "$php_share_internal_startpage" == "$expected_share_internal_startpage" ]]; then
#	green_text "php .gui/share_internal.php _share_test_case"
#else
#	error_msg="php .gui/share_internal.php _share_test_case failed.\nGot:\n$php_share_internal_startpage\nExpected:\n$expected_share_internal_startpage"
#	red_text "$error_msg"
#	ERRORS+=("$error_msg")
#fi

export user_id="test_user"

php_share_internal_startpage_test_user_id=$(php share_internal.php | sed -e 's#<!--\s*[^-]*\s*-->##g' -e 's#^\s*##' | grep -v '^\s*$' | tr '\n' ' ' | sed -e 's#\s\s*# #g' -e 's#\s*$##' -e 's#^\s##' 2>&1)
expected_share_internal_startpage_test_user_id="Using sharesPath ./_share_test_case/ <script src='plotly-latest.min.js'></script> <script src='share.js'></script> <script src='share_graphs.js'></script> <link href=\"./share.css\" rel=\"stylesheet\" /> <div id=\"breadcrumb\"></div> <a class='_share_link' href=\"share.php?user_id=test_user&experiment_name=ClusteredStatisticalTestDriftDetectionMethod_NOAAWeather&share_path=./_share_test_case/\">ClusteredStatisticalTestDriftDetectionMethod_NOAAWeather</a><br> <a class='_share_link' href=\"share.php?user_id=test_user&experiment_name=ClusteredStatisticalTestDriftDetectionMethod_Powersupply&share_path=./_share_test_case/\">ClusteredStatisticalTestDriftDetectionMethod_Powersupply</a><br> <script>createBreadcrumb('./test_user//');</script>"

if [[ "$php_share_internal_startpage_test_user" == "$expected_share_internal_startpage_test_user" ]]; then
	green_text "php .gui/share_internal.php _share_test_case/test_user"
else
	error_msg="php .gui/share_internal.php _share_test_case/test_user failed.\nGot:\n$php_share_internal_startpage_test_user\nExpected:\n$expected_share_internal_startpage_test_user"
	red_text "$error_msg"
	ERRORS+=("$error_msg")
fi

export experiment_name_name="non-existing-experiment_name"

#php_share_internal_startpage_test_user_non_existing_experiment_name=$(php share_internal.php | sed -e 's#<!--\s*[^-]*\s*-->##g' -e 's#^\s*##' | grep -v '^\s*$' | tr '\n' ' ' | sed -e 's#\s\s*# #g' -e 's#\s*$##' -e 's#^\s##' 2>&1)
#expected_share_internal_startpage_test_user_non_existing_experiment_name="Using sharesPath ./_share_test_case/Could not create user folder"

#if [[ "$php_share_internal_startpage_test_user_non_existing_experiment_name" == "$expected_share_internal_startpage_test_user_non_existing_experiment_name" ]]; then
#	green_text "php .gui/share_internal.php _share_test_case/test_user/non-existing-experiment_name"
#else
#	error_msg="php .gui/share_internal.php _share_test_case/test_user/non-existing-experiment_name failed.\nGot:\n$php_share_internal_startpage_test_user_non_existing_experiment_name\nExpected:\n$expected_share_internal_startpage_test_user_non_existing_experiment_name\n\n"
#	red_text "$error_msg"
#	ERRORS+=("$error_msg")
#fi

#export run_id=0
#export experiment_name_name="ClusteredStatisticalTestDriftDetectionMethod_NOAAWeather"

#php_share_internal_startpage_test_user_id=$(php share_internal.php | sed -e 's#<!--\s*[^-]*\s*-->##g' -e 's#^\s*##' | grep -v '^\s*$' | tr '\n' ' ' | sed -e 's#\s\s*# #g' -e 's#\s*$##' -e 's#^\s##' 2>&1)
#expected_share_internal_startpage_test_user_id="Using sharesPath ./_share_test_case/ <script src='plotly-latest.min.js'></script> <script src='share.js'></script> <script src='share_graphs.js'></script> <link href=\"./share.css\" rel=\"stylesheet\" /> <div id=\"breadcrumb\"></div> <a class='_share_link' href=\"share.php?user_id=test_user&experiment_name=ClusteredStatisticalTestDriftDetectionMethod_NOAAWeather&share_path=./_share_test_case/\">ClusteredStatisticalTestDriftDetectionMethod_NOAAWeather</a><br> <a class='_share_link' href=\"share.php?user_id=test_user&experiment_name=ClusteredStatisticalTestDriftDetectionMethod_Powersupply&share_path=./_share_test_case/\">ClusteredStatisticalTestDriftDetectionMethod_Powersupply</a><br> <script>createBreadcrumb('./test_user//');</script>"

#if [[ "$php_share_internal_startpage_test_user" == "$expected_share_internal_startpage_test_user" ]]; then
#	green_text "php .gui/share_internal.php _share_test_case/test_user"
#else
#	error_msg="php .gui/share_internal.php _share_test_case/test_user/ClusteredStatisticalTestDriftDetectionMethod_NOAAWeather failed.\nGot:\n$php_share_internal_startpage_test_user\nExpected:\n$expected_share_internal_startpage_test_user"
#	red_text "$error_msg"
#	ERRORS+=("$error_msg")
#fi

export share_path=_share_test_case
export user_id=test_user
export experiment_name=ClusteredStatisticalTestDriftDetectionMethod_NOAAWeather
export run_id=0

original_dir=$(pwd)

share_internal_output=$(php share_internal.php 2>&1)

share_output_must_contain=(
	"0.696001762308624316588634428626"
	"BoTorch"
	"trial_status"
	"0.183587289507441547842248041889"
	"feature_proportion"
	"499,74_0,FAILED,BoTorch,,1000,0.250000000000000000000000000000,0.000000000000000000000000000000,1"
	"results_csv_bare"
	"job_infos_csv"
	"find_closest_element_behind_and_copy_content_to_clipboard"
	"Experiment parameters"
	"breadcrumb"
	"createBreadcrumb"
	"./_share_test_case/test_user/ClusteredStatisticalTestDriftDetectionMethod_NOAAWeather/0"
	"Best results"
	"Parameter"
	"2d-Scatter-Plots"
	"3d-Scatter-Plots"
	"Sobol"
)

for i in "${share_output_must_contain[@]}"; do
	if echo "$share_internal_output" | grep "$i" 2>/dev/null >/dev/null; then
		true
	else
		error_msg="php share_internal.php does not contain $i"
		red_text "$error_msg"
		ERRORS+=("$error_msg")
	fi
done

if [ ${#ERRORS[@]} -eq 0 ]; then
	green_text "No errors"
else
	red_text "=> ERRORS => ERRORS => ERRORS =>"
	for i in "${ERRORS[@]}"; do
		red_text "$i"
		echo ""
	done
fi

exit ${#ERRORS[@]}
