#!/bin/bash

function echoerr() {
        echo "$@" 1>&2
}

function yellow_text {
        echoerr -e "\e\033[0;33m$1\e[0m"
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

function green_text {
        echoerr -e "\e\033[0;32m$1\e[0m"
}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd test_wronggoing_stuff.bin

function echoerr() {
        echo "$@" 1>&2
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

set -e
set -o pipefail

function calltracer () {
	yellow_text "Git status hash:"
	git rev-parse HEAD
        red_text 'Error occured in file/line:'
        caller
}

trap 'calltracer' ERR

function help () {
        echo "Possible options:"
	echo "  --use-ram-tests                                    Run test that allocates more and more memory"
        echo "  --help                                             this help"
        echo "  --debug                                            Enables debug mode (set -x)"
	echo "  --num_parallel_jobs=n                              Number of parallel jobs"
	echo "  --worker_timeout=n                                 Number of minutes for a single-worker to timeout"
	echo "  --time=n                                           Max runtime in minutes"
	echo "  --max_eval=n                                       Max number of evals"
	echo "  --not_all_at_once                                  Run all jobs at once in the scheduler instead of one-by-one"
        exit $1
}

function join_by {
	local d=${1-} f=${2-}
	if shift 2; then
		printf %s "$f" "${@/#/$d}"
	fi
}

export useramtests=0

export max_eval=200
export num_parallel_jobs=20
export worker_timeout=30
export mem_gb=30
export runtime=300
export not_all_at_once=0

for i in $@; do
        case $i in
		--mem_gb=*)
			mem_gb="${i#*=}"
			shift
			;;
		--worker_timeout=*)
			worker_timeout="${i#*=}"
			shift
			;;
		--num_parallel_jobs=*)
			num_parallel_jobs="${i#*=}"
			shift
			;;
		--time=*)
			runtime="${i#*=}"
			shift
			;;
		--max_eval=*)
			max_eval="${i#*=}"
			shift
			;;
                --not_all_at_once)
                        not_all_at_once=1
                        shift
                        ;;
                --use-ram-tests)
                        useramtests=1
                        shift
                        ;;
                -h|--help)
                        help 0
                        ;;
                --debug)
                        set -x
                        ;;
                *)
                        red_text "Unknown parameter $i" >&2
                        help 1
                        ;;
        esac
done

PARTITION="alpha"
NUM_GPUS=0

if command -v nvidia-smi 2>/dev/null >/dev/null; then
	NUM_GPUS=$(nvidia-smi --list-gpus | wc -l)
fi

if [[ "$NUM_GPUS" -ne "0" ]]; then
	NUM_GPUS=1
fi

cd ..
cd ..

#if [[ -d runs/example_network/ ]]; then
#	rm -rf runs/example_network/
#fi

# run_program = .tests/example_network/run.sh --epochs=%(epochs) --learning_rate=%(learning_rate) --validation_split=%(validation_split) --width=%(width) --height=%(height)

if [[ "$not_all_at_once" -eq "1" ]]; then
	 ./omniopt \
		 --partition=$PARTITION \
		 --experiment_name=example_network \
		 --mem_gb=$mem_gb \
		 --time=$runtime \
		 --worker_timeout=$worker_timeout \
		 --max_eval=$max_eval \
		 --num_parallel_jobs=$num_parallel_jobs \
		 --gpus=$NUM_GPUS \
		 --run_program=$(echo "bash $SCRIPT_DIR/example_network/run.sh --learning_rate=%(learning_rate) --epochs=%(epochs) --validation_split=%(validation_split) --width=%(width) --height=%(height)" | base64 -w 0)\
		 --parameter width range 20 80 int \
		 --parameter height range 20 80 int \
		 --parameter validation_split range 0 0.4 float \
		 --parameter learning_rate range 0.001 0.4 float \
		 --parameter epochs range 1 10 int \
		 --not_all_at_once \
		 --debug
 else
	 ./omniopt \
		 --partition=$PARTITION \
		 --experiment_name=example_network \
		 --mem_gb=$mem_gb \
		 --time=$runtime \
		 --worker_timeout=$worker_timeout \
		 --max_eval=$max_eval \
		 --num_parallel_jobs=$num_parallel_jobs \
		 --gpus=$NUM_GPUS \
		 --run_program=$(echo "bash $SCRIPT_DIR/example_network/run.sh --learning_rate=%(learning_rate) --epochs=%(epochs) --validation_split=%(validation_split) --width=%(width) --height=%(height)" | base64 -w 0)\
		 --parameter width range 20 80 int \
		 --parameter height range 20 80 int \
		 --parameter validation_split range 0 0.4 float \
		 --parameter learning_rate range 0.001 0.4 float \
		 --parameter epochs range 1 10 int \
		 --debug
fi

exit $?
