#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .shellscript_functions

exit_code=0

if command -v python3 2>/dev/null >/dev/null; then
	if [[ -z $RUN_WITH_COVERAGE ]]; then
		if [[ -n $1 ]]; then
			python3 .tests/unit_tests_plots.py $*
			exit_code=$?
		else
			python3 .tests/unit_tests_plots.py .*.py
			exit_code=$?
		fi
	else
		if [[ -n $1 ]]; then
			coverage run -p .tests/unit_tests_plots.py $*
		else
			coverage run -p .tests/unit_tests_plots.py .*.py
			exit_code=$?
		fi
	fi
else
	echo "Warning: python3 is not installed. Cannot run find_typos_in_python"
fi


exit $exit_code
