#!/bin/bash

if [[ $RUNNER_OS == 'Linux' ]]; then
	if grep -q '^ID=ubuntu' /etc/os-release; then
		sudo apt-get update || sudo apt-get update || sudo apt-get update
		sudo apt-get install -y xterm whiptail python3-dev php-cli unzip curl 2to3 python3-lib2to3 python3-toolz php-mbstring bc util-linux
		curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
		sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
	else
		echo "Invalid OS for pipeline. Only works with Ubuntu"
		exit 1
	fi
else
	echo "Invalid OS detected"
	exit 2
fi
