#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"
cd ..

version=$1

cat > pyproject.toml <<EOF
[project]
name = "omniopt2"
description = "Automatic highly parallelized hyperparameter optimizer based on Ax/Botorch"
authors = [
  {email = "norman.koch@tu-dresden.de"},
  {name = "Norman Koch"}
]
version = "${version}"

readme = "README.md"
dynamic = ["dependencies"]

[tool.setuptools]
py-modules = []

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt", "test_requirements.txt"]}
EOF

exit 0
