#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"

cd ..

source .shellscript_functions

python3 .tools/find_duplicate_functions.py $*
exit_code=$?

exit $exit_code
