services:
  slurmfrontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        container_name: slurm-frontend
        shm_size: '4g'
        hostname: slurmfrontend
        user: admin
        volumes:
                - shared-vol:/home/admin
                - ../../:/oo_dir
        ports:
                - 8888:8888
  slurmmaster:
        build:
          context: ./master
          dockerfile: Dockerfile
        container_name: slurm-master
        shm_size: '4g'
        hostname: slurmmaster
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
                - ../../:/oo_dir
        environment:
                - SLURM_CPUS_ON_NODE=1
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        build:
          context: ./node
          dockerfile: Dockerfile
        container_name: slurm-node1
        shm_size: '4g'
        hostname: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
                - ../../:/oo_dir
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurmmaster
  slurmnode2:
        build:
          context: ./node
          dockerfile: Dockerfile
        container_name: slurm-node1
        shm_size: '4g'
        hostname: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin:nocopy
                - ../../:/oo_dir
        environment:
                - SLURM_NODENAME=slurmnode2
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurmmaster
volumes:
        shared-vol:
