#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath "$0"))

cd $SCRIPT_DIR

if [[ ! -e ax ]]; then
	ln -s ../../ ax
fi

docker-compose build slurmfrontend

docker-compose -f docker-compose.yml up -d

rm -rf ax
