#!/bin/bash

set -e

SCRIPT_DIR=$(dirname $(realpath "$0"))

cd $SCRIPT_DIR

for i in frontend master node; do
	cp slurm.conf $i/
done

docker-compose build slurmmaster
docker-compose build slurmfrontend
for nodename in $(cat docker-compose.yml | grep "slurmnode[0-9]:" | sed -e 's#^\s*##' -e 's#:\s*##'); do
	docker-compose build $nodename
done

docker-compose -f docker-compose.yml up -d --remove-orphans

for i in frontend master node; do
	rm $i/slurm.conf
done
