#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath "$0"))

cd $SCRIPT_DIR

docker-compose build slurmmaster
docker-compose build slurmfrontend
docker-compose build slurmnode1
docker-compose build slurmnode2
docker-compose build slurmnode3

docker-compose -f docker-compose.yml up -d
