#!/bin/bash

# Default values

# Help message
help_message() {
	echo "Usage: docker [OPTIONS]"
	echo "Options:"
	echo "  --help             Show this help message"
}

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
	case $1 in
		--help)
			help_message
			exit 0
			;;
	esac
	shift
done

is_package_installed() {
	dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -c "ok installed"
}

UPDATED_PACKAGES=0

# Check if Docker is installed
if ! command -v docker &>/dev/null && command -v apt >/dev/null; then
	if [[ ! -e /etc/apt/sources.list ]]; then
		echo "/etc/apt/sources.list not found. Cannot continue. You must install docker manually."
		exit 1
	fi
	echo "Docker not found. Installing Docker..."
	echo "Enabling non-free repository..."
	sed -i 's/main$/main contrib non-free/g' /etc/apt/sources.list
	echo "Enabled! non-free repository."

	# Update package lists
	if [[ $UPDATED_PACKAGES == 0 ]]; then
		sudo apt update || {
			echo "apt-get update failed. Are you online?"
			exit 2
		}

		UPDATED_PACKAGES=1
	fi


	# Install Docker
	sudo apt install -y docker.io || {
		echo "sudo apt install -y docker.io failed"
		exit 3
	}
fi

if ! command -v wget &>/dev/null; then
	# Update package lists
	if [[ $UPDATED_PACKAGES == 0 ]]; then
		sudo apt update || {
			echo "apt-get update failed. Are you online?"
			exit 3
		}

		UPDATED_PACKAGES=1
	fi

	sudo apt-get install -y wget || {
		echo "sudo apt install -y wget failed"
		exit 3
	}
fi

if ! command -v git &>/dev/null; then
	# Update package lists
	if [[ $UPDATED_PACKAGES == 0 ]]; then
		sudo apt update || {
			echo "apt-get update failed. Are you online?"
			exit 3
		}

		UPDATED_PACKAGES=1
	fi

	sudo apt-get install -y git || {
		echo "sudo apt install -y git failed"
		exit 4
	}
fi

echo "=== Current git hash before auto-pulling ==="
git rev-parse HEAD
echo "=== Current git hash before auto-pulling ==="

git pull

function die {
	echo $1
	exit 1
}

sudo docker-compose build && sudo docker-compose up -d || echo "Failed to build container"

if [[ ! -z $* ]]; then
	docker run -i -t ax_omniopt2 bash /var/opt/omniopt/$*
fi
