#!/bin/bash

export ORIGINAL_PWD=$(pwd)

function echoerr() {
        echo "$@" 1>&2
}

function red_text {
        echoerr -e "\e[31m$1\e[0m"
}

set -e
set -o pipefail

function calltracer () {
        echo 'Last file/last line:'
        caller

	echo "Runtime: $(displaytime $SECONDS)"
}
trap 'calltracer' ERR

plot_type="default"
help=0

for i in $@; do
        case $i in
		--plot_type=*)
			plot_type="${i#*=}"
			;;
                --help|-h)
			help=1
                        ;;
                --debug)
                        set -x
                        ;;
        esac
done

#SBATCH --signal=B:USR1@120

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -n "${SLURM_JOB_ID:-}" ] ; then
	SLURM_FILE_SCRIPT_DIR=$(scontrol show job "$SLURM_JOB_ID" | awk -F= '/Command=/{print $2}')
	SLURM_FILE_SCRIPT_DIR=$(dirname $SLURM_FILE_SCRIPT_DIR)

	if [[ -d $SLURM_FILE_SCRIPT_DIR ]]; then
		SCRIPT_DIR="$SLURM_FILE_SCRIPT_DIR"
	else
		echo "SLURM_FILE_SCRIPT_DIR $SLURM_FILE_SCRIPT_DIR not found, even though SLURM_JOB_ID exists ($SLURM_JOB_ID). Using SCRIPT_DIR=$SCRIPT_DIR"
	fi
fi

cd $ORIGINAL_PWD

source $SCRIPT_DIR/.shellscript_functions
source $SCRIPT_DIR/.general.sh

echo "Showing plot type: $plot_type"

set +e
if [[ "$plot_type" == "default" ]]; then
	OUTPUT=$(python3 $SCRIPT_DIR/.omniopt_plot.py $* 2>&1)
	exit_code=$?
elif [[ "$plot_type" == "general" ]]; then
	OUTPUT=$(python3 $SCRIPT_DIR/.omniopt_plot_general.py $* 2>&1)
	exit_code=$?
else
	echo "Unknown --plot_type: $plot_type"
	false
	exit_code=$?
fi
set -e

if [[ "$exit_code" -ne "0" ]]; then
	if command -v whiptail 2>/dev/null >/dev/null; then
		if [[ -z $NO_WHIPTAIL ]]; then
			error_message "$OUTPUT"
		else
			echo $OUTPUT
		fi
	else
		echo -- "$OUTPUT"
	fi
else
	echo "$OUTPUT"
fi

echo "Runtime: $(displaytime $SECONDS)"
