name: Cache Omniax Venv

on:
  workflow_call:
    inputs:
      requirements:
        required: true
        type: string

jobs:
  cache-venv:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract date
        id: date
        run: echo "today=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Cache omniax_venvs
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.omniax_venvs
          key: venv-${{ steps.date.outputs.today }}-${{ hashFiles(inputs.requirements) }}
          restore-keys: |
            venv-${{ steps.date.outputs.today }}-
            venv-
