name: Common Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Update package lists
        run: sudo apt-get update || exit 1

      - name: Install common dependencies
        run: |
          if [[ $RUNNER_OS == 'Linux' ]]; then
            sudo apt-get install -y \
              xterm whiptail python3-dev php-cli unzip curl 2to3 \
              python3-lib2to3 python3-toolz php-mbstring bc util-linux
            if grep -q '^ID=ubuntu' /etc/os-release; then
              curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
              sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
            else
              echo "Invalid OS for pipeline. Only works with Ubuntu"
              exit 1
            fi
          else
              echo "Invalid OS detected"
              exit 2
          fi
